version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: api_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    container_name: api_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: api_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./init_rabbitmq.sh:/app/init_rabbitmq.sh
    restart: always

volumes:
  pgdata:
